# Generated by Django 4.2.6 on 2024-09-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ('username',)},
        ),
    ]
